config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources :team_members

  root to: 'welcome#index'

  resources :properties

end

app/models/property.rb
class Property < ActiveRecord::Base
  validates :title, :bedrooms, :price, :status, :description, :floorplan, :tenure, :council_tax_band, :chain_free, :property_name_number, :property_street, :property_town, :property_county, :property_postcode, :property_style, presence: true
  validates :bedrooms, numericality: {greater_than_or_equal_to: 1}
end

app/models/team_member.rb
class TeamMember < ActiveRecord::Base
  validates :name, :description, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :set_team_members, :set_properties, :set_latest_properties

  private

  def set_team_members
    @team_members = TeamMember.all
  end

  def set_properties
    @properties = Property.all
  end

  def set_latest_properties
    @latest_properties = Property.where('created_at > ?', 1.days.ago)
  end

end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  before_action :set_property, only: [:show, :edit, :update, :destroy, :format_address]


  # GET /properties
  # GET /properties.json
  def index
    @properties = Property.all
  end

  # GET /properties/1
  # GET /properties/1.json
  def show
  end

  # GET /properties/new
  def new
    @property = Property.new
  end

  # GET /properties/1/edit
  def edit
  end

  # POST /properties
  # POST /properties.json
  def create
    @property = Property.new(property_params)

    respond_to do |format|
      if @property.save
        format.html { redirect_to @property, notice: 'Property was successfully created.' }
        format.json { render :show, status: :created, location: @property }
      else
        format.html { render :new }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /properties/1
  # PATCH/PUT /properties/1.json
  def update
    respond_to do |format|
      if @property.update(property_params)
        format.html { redirect_to @property, notice: 'Property was successfully updated.' }
        format.json { render :show, status: :ok, location: @property }
      else
        format.html { render :edit }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /properties/1
  # DELETE /properties/1.json
  def destroy
    @property.destroy
    respond_to do |format|
      format.html { redirect_to properties_url, notice: 'Property was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  helper_method :format_address

  def format_address
    if @property.property_village.empty?
      "#{@property.property_street}, #{@property.property_town}"
    else 
      "#{@property.property_street}, #{@property.property_village}"
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_property
      @property = Property.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def property_params
      params.require(:property).permit(:title, :bedrooms, :map_url, :price, :status, :description, :floorplan, :featured_property, :tenure, :remaining_lease, :ground_rent, :service_charge, :council_tax_band, :chain_free, :property_name_number, :property_street, :property_village, :property_town, :property_county, :property_postcode, :property_style)
    end
end

app/controllers/team_members_controller.rb
class TeamMembersController < ApplicationController
  before_action :set_team_member, only: [:show, :edit, :update, :destroy]

  # GET /team_members
  # GET /team_members.json
  def index
    @team_members = TeamMember.all
  end

  # GET /team_members/1
  # GET /team_members/1.json
  def show
  end

  # GET /team_members/new
  def new
    @team_member = TeamMember.new
  end

  # GET /team_members/1/edit
  def edit
  end

  # POST /team_members
  # POST /team_members.json
  def create
    @team_member = TeamMember.new(team_member_params)

    respond_to do |format|
      if @team_member.save
        format.html { redirect_to @team_member, notice: 'Team member was successfully created.' }
        format.json { render :show, status: :created, location: @team_member }
      else
        format.html { render :new }
        format.json { render json: @team_member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /team_members/1
  # PATCH/PUT /team_members/1.json
  def update
    respond_to do |format|
      if @team_member.update(team_member_params)
        format.html { redirect_to @team_member, notice: 'Team member was successfully updated.' }
        format.json { render :show, status: :ok, location: @team_member }
      else
        format.html { render :edit }
        format.json { render json: @team_member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /team_members/1
  # DELETE /team_members/1.json
  def destroy
    @team_member.destroy
    respond_to do |format|
      format.html { redirect_to team_members_url, notice: 'Team member was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_team_member
      @team_member = TeamMember.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def team_member_params
      params.require(:team_member).permit(:name, :description, :image_url, :email)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/helpers/team_members_helper.rb
module TeamMembersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EstateAgents</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<header>
  <h1>ESTATE AGENT NAME OR LOGO</h1>
  <span>Some strapline</span>
  <p>1 The Street<br />TownName<br />County<br />PostCode<br /><span>Tel</span></p>
  <nav>
    <ul>
      <li>
        <%= link_to "Home", controller: :welcome, action: :index %>
      </li>
      <li>
        <%= link_to "Our Team", controller: :team_members, action: :index %>
      </li>
      <li>
        <%= link_to "Properties For Sale", controller: :properties, action: :index %>
      </li>
    </ul>
  </nav>
</header>
<hr>
<%= yield %>
<hr>
<footer>
  <div>
    <h2>Meet the team</h2>
    <%= render 'team_members/member', title: "Meet the team" %>
  </div>
  <nav>
    <ul>
      <li>
        <a href="#">FooterLink1</a>
      </li>
      <li>
        <a href="#">FooterLink2</a>
      </li>
      <li>
        <a href="#">FooterLink3</a>
      </li>
    </ul>
  </nav>
  <ul>
    <li>
      <a href="#">Facebook</a>
    </li>
    <li>
      <a href="#">Twitter</a>
    </li>
    <li>
      <a href="#">G+</a>
    </li>
  </ul>
  <p>Footer text goes here</p>
</footer>
</body>
</html>

app/views/properties/_form.html.erb
<%= form_for(@property) do |f| %>
  <% if @property.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@property.errors.count, "error") %> prohibited this property from being saved:</h2>

      <ul>
      <% @property.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :property_name_number %><br>
    <%= f.text_field :property_name_number %>
  </div>
  <div class="field">
    <%= f.label :property_street %><br>
    <%= f.text_field :property_street %>
  </div>
  <div class="field">
    <%= f.label :property_village %><br>
    <%= f.text_field :property_village %>
  </div>
  <div class="field">
    <%= f.label :property_town %><br>
    <%= f.text_field :property_town %>
  </div>
  <div class="field">
    <%= f.label :property_county %><br>
    <%= f.text_field :property_county %>
  </div>
  <div class="field">
    <%= f.label :property_postcode %><br>
    <%= f.text_field :property_postcode %>
  </div>
  <div class="field">
    <%= f.label :property_style %><br>
    <%= f.select :property_style, [['DETACHED', 'DETACHED'],['SEMI-DETACHED', 'SEMI-DETACHED'],['TERRACED', 'TERRACED'],['OTHER', 'OTHER']], {include_blank: true} %>
  </div>
  <div class="field">
    <%= f.label :bedrooms %><br>
    <%= f.text_field :bedrooms %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.select :status, [['FOR SALE', 'FOR SALE'],['UNDER OFFER', 'UNDER OFFER'],['SSTC', 'SSTC'],['SOLD', 'SOLD']], {include_blank: true} %>
  </div>
  <div class="field">
    <%= f.label :map_url %><br>
    <%= f.text_field :map_url %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :floorplan %><br>
    <%= f.text_field :floorplan %>
  </div>
  <div class="field">
    <%= f.label :featured_property %><br>
    <%= f.select :featured_property, [['YES', true],['NO', false]], {include_blank: true} %>
  </div>
  <div class="field">
    <%= f.label :tenure %><br>
    <%= f.select :tenure, [['FREEHOLD', 'FREEHOLD'],['LEASEHOLD', 'LEASEHOLD']], {include_blank: true} %>
  </div>
  <div class="field">
    <%= f.label :remaining_lease %><br>
    <%= f.text_field :remaining_lease %>
  </div>
  <div class="field">
    <%= f.label :ground_rent %><br>
    <%= f.text_field :ground_rent %>
  </div>
  <div class="field">
    <%= f.label :service_charge %><br>
    <%= f.text_field :service_charge %>
  </div>
  <div class="field">
    <%= f.label :council_tax_band %><br>
    <%= f.text_field :council_tax_band %>
  </div>
  <div class="field">
    <%= f.label :chain_free %><br>
    <%= f.select :chain_free, [['YES', true],['NO', false]], {include_blank: true} %>
  </div>

  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/properties/_properties.html.erb
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Bedrooms</th>
      <th>Price</th>
      <th>Status</th>
      <th colspan="5"></th>
    </tr>
  </thead>

  <tbody>
    <% @properties.each do |property| %>
      <tr>
        <td><%= property.title %></td>
        <td><%= property.bedrooms %></td>
        <td><%= property.price %></td>
        <td><%= property.status %></td>
        <td><%= link_to 'Show', property %></td>
        <td><%= link_to 'Edit', edit_property_path(property) %></td>
        <td><%= link_to 'Destroy', property, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/properties/edit.html.erb
<h1>Editing property</h1>

<%= render 'form' %>

<%= link_to 'Show', @property %> |
<%= link_to 'Back', properties_path %>

app/views/properties/index.html.erb
<section>
  <form>
    <select names="min_beds" >
      <option value selected="selected">Minimum number of bedrooms</option>
      <option>1</option>
      <option>2</option>
      <option>3</option>
      <option>4</option>
      <option>5+</option>
    </select>
    <select names="max_beds" >
      <option value selected="selected">Maximum number of bedrooms</option>
      <option>No maximum</option>
      <option>1</option>
      <option>2</option>
      <option>3</option>
      <option>4</option>
    </select>
    <select names="type" >
      <option value selected="selected">Property Type</option>
      <option>House</option>
      <option>Flat/Appartment</option>
      <option>Bungalow</option>
      <option>Other</option>
    </select>    
    <select names="min_price" >
      <option value selected="selected">Price min</option>
      <option>No minimum</option>
      <option>&pound;50,000</option>
      <option>&pound;100,000</option>
      <option>&pound;150,000</option>
      <option>&pound;200,000</option>
      <option>&pound;250,000</option>
      <option>&pound;300,000</option>
      <option>&pound;400,000</option>
      <option>&pound;500,000</option>
    </select>
    <select names="max_price" >
      <option value selected="selected">Price max</option>
      <option>No maximum</option>
      <option>&pound;100,000</option>
      <option>&pound;150,000</option>
      <option>&pound;200,000</option>
      <option>&pound;250,000</option>
      <option>&pound;300,000</option>
      <option>&pound;400,000</option>
      <option>&pound;500,000</option>
    </select>
    <input type="submit" value="Search">
  </form>
</section>
<!-- <section>
  <form>
    <select names="min_beds" >
      <option value selected="selected">Minimum number of bedrooms</option>
      <option>1</option>
      <option>2</option>
      <option>3</option>
      <option>4</option>
      <option>5+</option>
    </select>
    <select names="max_beds" >
      <option value selected="selected">Maximum number of bedrooms</option>
      <option>No maximum</option>
      <option>1</option>
      <option>2</option>
      <option>3</option>
      <option>4</option>
    </select>
    <select names="type" >
      <option value selected="selected">Property Type</option>
      <option>House</option>
      <option>Flat/Appartment</option>
      <option>Bungalow</option>
      <option>Other</option>
    </select> 
    <select names="min_price" >
      <option value selected="selected">Price min per month</option>
      <option>No minimum</option>
      <option>&pound;300</option>
      <option>&pound;400</option>
      <option>&pound;500</option>
      <option>&pound;600</option>
      <option>&pound;700</option>
      <option>&pound;800</option>
      <option>&pound;900</option>
      <option>&pound;1,000</option>
    </select>
    <select names="max_price" >
      <option value selected="selected">Price max per month</option>
      <option>No maximum</option>
      <option>&pound;500</option>
      <option>&pound;600</option>
      <option>&pound;700</option>
      <option>&pound;800</option>
      <option>&pound;900</option>
      <option>&pound;1,000</option>
      <option>&pound;1,500</option>
    </select>
    <input type="submit" value="Search">
  </form>
</section> -->
<%= render 'properties/properties' %>

<br>

<%= link_to 'New Property', new_property_path %>

app/views/properties/new.html.erb
<h1>New property</h1>

<%= render 'form' %>

<%= link_to 'Back', properties_path %>

app/views/properties/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @property.title %>
</p>

<p> 
  <strong>Address:</strong>
  <%= format_address %>
</p>

<p>
  <strong>Price:</strong>
  <%= @property.price %>
</p>

<p>
  <strong>Status:</strong>
  <%= @property.status %>
</p>

<p> 
  <strong>Description:</strong>
  <%= @property.description %>
</p>

<p> 
  <strong>Tenure:</strong>
  <%= @property.tenure %>
</p>

<% if @property.tenure == 'LEASEHOLD' %>
  <p> 
    <strong>Remaining Lease:</strong>
    <%= @property.remaining_lease %>
  </p>

  <p> 
    <strong>Ground Rent:</strong>
    <%= @property.ground_rent %>
  </p>

  <p> 
    <strong>Service Charge:</strong>
    <%= @property.service_charge %>
  </p>
<% end %>

<p>
  <strong>Map URL:</strong>
  <%= @property.map_url %>
</p>

<p> 
  <strong>Floorplan:</strong>
  <%= @property.floorplan %>
</p>


<h3>Info:</h3>

<p> 
  <strong>Style:</strong>
  <%= @property.property_style %>
</p>

<p>
  <strong>Bedrooms:</strong>
  <%= @property.bedrooms %>
</p>

<p> 
  <strong>Featured Property?:</strong>
  <%= @property.featured_property %>
</p>

<p> 
  <strong>Council Tax Band:</strong>
  <%= @property.council_tax_band %>
</p>

<p> 
  <strong>Chain Free?</strong>
  <%= @property.chain_free %>
</p>






<%= link_to 'Edit', edit_property_path(@property) %> |
<%= link_to 'Back', properties_path %>

app/views/team_members/_form.html.erb
<%= form_for(@team_member) do |f| %>
  <% if @team_member.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@team_member.errors.count, "error") %> prohibited this team_member from being saved:</h2>

      <ul>
      <% @team_member.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br>
    <%= f.text_field :image_url %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/team_members/_member.html.erb
<% @team_members.each do |member| %>
  <section>
  <h3><%= member.name %></h3>
  <p><%= member.description %></p>  
  </section>
<% end %>

app/views/team_members/edit.html.erb
<h1>Editing team_member</h1>

<%= render 'form' %>

<%= link_to 'Show', @team_member %> |
<%= link_to 'Back', team_members_path %>

app/views/team_members/index.html.erb
<h1>Listing team_members</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Image url</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @team_members.each do |team_member| %>
      <tr>
        <td><%= team_member.name %></td>
        <td><%= team_member.description %></td>
        <td><%= team_member.image_url %></td>
        <td><%= team_member.email %></td>
        <td><%= link_to 'Show', team_member %></td>
        <td><%= link_to 'Edit', edit_team_member_path(team_member) %></td>
        <td><%= link_to 'Destroy', team_member, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Team member', new_team_member_path %>

app/views/team_members/new.html.erb
<h1>New team_member</h1>

<%= render 'form' %>

<%= link_to 'Back', team_members_path %>

app/views/team_members/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @team_member.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @team_member.description %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @team_member.image_url %>
</p>

<p>
  <strong>Email:</strong>
  <%= @team_member.email %>
</p>

<%= link_to 'Edit', edit_team_member_path(@team_member) %> |
<%= link_to 'Back', team_members_path %>

app/views/welcome/index.html.erb
<div>
  <h2>Testimonials</h2>
  <article>
  <header>Mr Smith</header>
  <p>Text about how great the service at [business name] is...</p>
  </article>
</div>
<div>
  <h2>Estate Agents [Placename]</h2>
  <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>
</div>
<h2>Properties for sale search</h2>
<section>
  <form>
    <select names="min_beds" >
      <option value selected="selected">Minimum number of bedrooms</option>
      <option>1</option>
      <option>2</option>
      <option>3</option>
      <option>4</option>
      <option>5+</option>
    </select>
    <select names="max_beds" >
      <option value selected="selected">Maximum number of bedrooms</option>
      <option>No maximum</option>
      <option>1</option>
      <option>2</option>
      <option>3</option>
      <option>4</option>
    </select>
    <select names="type" >
      <option value selected="selected">Property Type</option>
      <option>House</option>
      <option>Flat/Appartment</option>
      <option>Bungalow</option>
      <option>Other</option>
    </select>    
    <select names="min_price" >
      <option value selected="selected">Price min</option>
      <option>No minimum</option>
      <option>&pound;50,000</option>
      <option>&pound;100,000</option>
      <option>&pound;150,000</option>
      <option>&pound;200,000</option>
      <option>&pound;250,000</option>
      <option>&pound;300,000</option>
      <option>&pound;400,000</option>
      <option>&pound;500,000</option>
    </select>
    <select names="max_price" >
      <option value selected="selected">Price max</option>
      <option>No maximum</option>
      <option>&pound;100,000</option>
      <option>&pound;150,000</option>
      <option>&pound;200,000</option>
      <option>&pound;250,000</option>
      <option>&pound;300,000</option>
      <option>&pound;400,000</option>
      <option>&pound;500,000</option>
    </select>
    <input type="submit" value="Search">
  </form>
</section>
<h2>Properties to Let search</h2>
<section>
  <form>
    <select names="min_beds" >
      <option value selected="selected">Minimum number of bedrooms</option>
      <option>1</option>
      <option>2</option>
      <option>3</option>
      <option>4</option>
      <option>5+</option>
    </select>
    <select names="max_beds" >
      <option value selected="selected">Maximum number of bedrooms</option>
      <option>No maximum</option>
      <option>1</option>
      <option>2</option>
      <option>3</option>
      <option>4</option>
    </select>
    <select names="type" >
      <option value selected="selected">Property Type</option>
      <option>House</option>
      <option>Flat/Appartment</option>
      <option>Bungalow</option>
      <option>Other</option>
    </select> 
    <select names="min_price" >
      <option value selected="selected">Price min per month</option>
      <option>No minimum</option>
      <option>&pound;300</option>
      <option>&pound;400</option>
      <option>&pound;500</option>
      <option>&pound;600</option>
      <option>&pound;700</option>
      <option>&pound;800</option>
      <option>&pound;900</option>
      <option>&pound;1,000</option>
    </select>
    <select names="max_price" >
      <option value selected="selected">Price max per month</option>
      <option>No maximum</option>
      <option>&pound;500</option>
      <option>&pound;600</option>
      <option>&pound;700</option>
      <option>&pound;800</option>
      <option>&pound;900</option>
      <option>&pound;1,000</option>
      <option>&pound;1,500</option>
    </select>
    <input type="submit" value="Search">
  </form>
</section>
<h2>Featured properties</h2>
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Bedrooms</th>
      <th>Price</th>
      <th>Status</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @properties.each do |property| %>
      <% if property.featured_property %>
        <tr>
          <td><%= property.title %></td>
          <td><%= property.bedrooms %></td>
          <td><%= property.price %></td>
          <td><%= property.status %></td>
          <td><%= link_to 'Show', property %></td>
          <td><%= link_to 'Edit', edit_property_path(property) %></td>
          <td><%= link_to 'Destroy', property, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>
<h2>Recently added properties</h2>
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Bedrooms</th>
      <th>Price</th>
      <th>Status</th>
      <th colspan="4"></th>
    </tr>
  </thead>
  <tbody>
  <% @latest_properties.each do |property| %>
    <tr>
      <td><%= property.title %></td>
      <td><%= property.bedrooms %></td>
      <td><%= property.price %></td>
      <td><%= property.status %></td>
      <td><%= link_to 'Show', property %></td>
      <td><%= link_to 'Edit', edit_property_path(property) %></td>
      <td><%= link_to 'Destroy', property, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
  </tbody>
</table> 
<br>

<%= link_to 'New Property', new_property_path %>